/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function calculateAgreement(peerPubKey: Buffer, privKey: Buffer): Buffer

export declare function calculateSignature(privKey: Buffer, message: Buffer): Buffer

export declare function generateKeyPair(): X25519KeyPair

export declare function getPublicFromPrivateKey(privKey: Buffer): Buffer

export declare function verifySignature(pubKey: Buffer, message: Buffer, sig: Buffer): boolean

export interface X25519KeyPair {
  pubKey: Buffer
  privKey: Buffer
}
